version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # env_file:
    #   - ./frontend/.env  ==> use it if you use .env in frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./ai-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./ai-backend/.env
